// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmicxzgrbjzlgqkwttnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtaWN4emdyYmp6bGdxa3d0dG5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODMwMDgsImV4cCI6MjA2ODM1OTAwOH0.BMGfUj9OfS9pM0FL_qjokLHJ7rwAJcU57O06XqnlsNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});